---
title: "article 1 : hungry bumble bees make plants flower early cutting holes their in leaves"
categories:
  - pollinators
description: 
 analysis of the article " hungry bumble bees make plants flower early cutting holes in their leaves.
author:
  - name: ___
    url: {}
date: 10-17-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# SOURCE OF THE ARTICLE WITH PUBLICATION DATE AND WORD COUNT: 

* Source of the article: https://www.sciencemag.org/news/2020/05/hungry-bumblebees-make-plants-flower-early-cutting-holes-their-leaves 

* date of article : May 21, 2020

* word count: 768

# - VOCABULARY

| **Word from the text** | **Synonym/definition in English**                  | **French translation**     |
|------------------------|----------------------------------------------------|----------------------------|
| gather                 | collect                                            | ramasser                   |
| nibble                 | to bite off, eat or chew in small bits             | petite bouchée, petit bout |
| spurring               | to incite (one) to take action                     | incitant                   |
| blossom                | flowers on trees : open                            | fleurir                    |
| schedule               | timetable                                          | programme                  |
| triggered              | to cause or begin                                  | déclencher, provoquer      |
| drought                | no rain                                            | sécheresse                 |
| incentive              | something that arouses someone to action           | avantage                   |
| mesh                   | an intertwined structure resembling a net; network | filet                      |
| widespread             | spread over a wide area                            | étendu                     |
| prompt                 | encourage                                          | pousser                    |

For the definitions and the translations I used Wordreference.

# ANALYSIS ABOUT THE STUDY

* Researchers?
    + ETH Zurich ( co-leader = Mark Mescher and Consuelo De Moraes )

* Published in? when (if mentioned)? 
    + Science

* General topic
    + The cut in a leaf by a pollinator enable an earlier flowering for the plant
    
* Procedure/what was examined 
    + To put mesh bags on Brassica nigra to avoid that the bumble bees feed
    + The bumble bees do cuts in leafs on the plant not still in flowering
    + The plants bloom in seventeen days ahead thirty-three days for the plants without cuts

* Conclusions/ discovery 
    + The bumble bees enable to bloom earlier with their cuts in leaf to found quicker food. The researchers think that the saliva of bumble bees contains chemical agents which look like to chemical agent of plant-eating insect. So the plant want a reproduction more quickly.

* Remaining questions
    + /
 
### réference de l'article:
Erik Stokstad, https://www.sciencemag.org/news/2020/05/hungry-bumblebees-make-plants-flower-early-cutting-holes-their-leaves, visited on October 3, 2020

 



